/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#4241bc',
          foreground: '#ffffff',
        },
        'on-background': '#0b1c30',
        outline: '#777585',
        'on-error-container': '#93000a',
        'on-surface-variant': '#464553',
        'on-tertiary-fixed': '#2f1500',
        'tertiary-fixed': '#ffdcc3',
        'on-tertiary-container': '#ffe8d9',
        'inverse-on-surface': '#eaf1ff',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed': '#0a006b',
        'inverse-primary': '#c1c1ff',
        'primary-fixed-dim': '#c1c1ff',
        error: '#ba1a1a',
        secondary: {
          DEFAULT: '#712ae2',
          foreground: '#ffffff',
        },
        'secondary-container': '#8a4cfc',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#a35700',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb77e',
        'inverse-surface': '#213145',
        'on-secondary-fixed': '#25005a',
        'on-primary-fixed-variant': '#3533b0',
        tertiary: '#804300',
        'primary-container': '#5b5bd6',
        'on-primary-container': '#edeaff',
        'on-surface': '#0b1c30',
        'on-primary': '#ffffff',
        'surface-tint': '#4e4ec9',
        'surface-variant': '#d3e4fe',
        surface: '#f8f9ff',
        'primary-fixed': '#e2dfff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed-variant': '#5a00c6',
        'surface-dim': '#cbdbf5',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f8f9ff',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        success: '#00a651',
      },
      spacing: {
        DEFAULT: '0.25rem',
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

